### PR TITLE
BorwserStack Image for inclusion in the readme

### PR DESCRIPTION
**Pull request by rstens**

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-vmvfjv-tools.pathfinder.gov.bc.ca/dashboard?id=common-forms-toolkit-pr-105

**Comment by rstens** [comment]
Well, this is the one way we know it is always there. We can create an images directory, but let's move forward with this for now.

**Comment by rstens** [comment]
I have sofar not been able to identify a good off-site candidate. So I have been following the lead of the guys at Registries who have been using this for quite some time.

**Comment by jujaga** [comment]
Ok. I'm going to have this PR merge into your other PR first so that the lineage comes together correctly on git. I'm not sure why two discrete PRs were made just for this...

**Pull request merged**
